#!/bin/bash
BASE_URL="https://8080-ik6uaye3mpqkgeo9uicky-c94c404e.manusvm.computer"

slides=(
"slide_01_loewenstarkes_team.html"
"slide_02_40_jahre.html"
"slide_03_rekord_2024.html"
"slide_04_zukunftsmaerkte_gesundheit.html"
"slide_05_zukunftsmaerkte_makeup.html"
"slide_06_300_produkte.html"
"slide_07_qualitaet.html"
"slide_08_aloe_vera.html"
"slide_09_health_mission.html"
"slide_10_nahrungsergaenzung.html"
"slide_11_body_mission.html"
"slide_12_zeitgard.html"
"slide_13_signature.html"
"slide_14_mood_infusion.html"
"slide_15_iconic_elixirs.html"
"slide_16_discovery_box.html"
"slide_17_werde_fan.html"
"slide_18_digital_tools.html"
"slide_19_verdienst.html"
"slide_20_fast_track.html"
"slide_21_karriere_teil1.html"
"slide_22_karriere_teil2.html"
"slide_23_business_track.html"
"slide_24_autokonzept.html"
"slide_25_autobonus.html"
"slide_26_auto_angebote.html"
"slide_26b_auto_angebote_2.html"
"slide_27_autoubergaben.html"
"slide_28_betreuung.html"
"slide_29_events.html"
"slide_30_traumreisen.html"
"slide_31_lina_intro.html"
"slide_32_lina_video.html"
"slide_33_lina_features.html"
"slide_34_einstieg.html"
"slide_35_startersets.html"
"slide_36_naechste_schritte.html"
"slide_37_vertrauen.html"
"slide_38_kontakt.html"
"slide_39_willkommen.html"
)

for slide in "${slides[@]}"; do
    echo "Downloading $slide..."
    curl -s "$BASE_URL/$slide" -o "$slide"
done

echo "Downloaded ${#slides[@]} slides"
